name: Update AvailProfiles

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Airports/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-availprofiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0  # Ensure we get the full history

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install jq

      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Airports directory contents:"
          ls -la Airports/ || echo "Airports directory not found"
          echo "AvailProfiles.json exists:"
          ls -la AvailProfiles.json || echo "AvailProfiles.json not found"
          echo "Git status:"
          git status
          echo "Changed files in this PR:"
          git diff --name-only HEAD~1 HEAD || echo "No changes detected"

      - name: Update AvailProfiles.json
        run: python .github/scripts/update_availprofiles.py

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet AvailProfiles.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add AvailProfiles.json
          git commit -m "Auto-update AvailProfiles.json"
          git push
